language: python
python:
  - "2.7"

before_install:
  - sudo apt-get update
  - sudo apt-get build-dep python-numpy python-scipy

install: "pip install -r requirements.txt --use-mirrors"

script: nosetests